apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlusers.api.edb-operator.com
spec:
  group: api.edb-operator.com
  names:
    kind: MySqlUser
    listKind: MySqlUserList
    plural: mysqlusers
    singular: mysqluser
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MySqlUser is the Schema for the mysqlusers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MySqlUserSpec defines the desired state of MySqlUser
            type: object
          status:
            description: MySqlUserStatus defines the observed state of MySqlUser
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
