apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlgrants.api.edb-operator.com
spec:
  group: api.edb-operator.com
  names:
    kind: MySQLGrant
    listKind: MySQLGrantList
    plural: mysqlgrants
    singular: mysqlgrant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MySQLGrant is the Schema for the mysqlgrants API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MySQLGrantSpec defines the desired state of MySQLGrant
          properties:
            "on":
              type: string
            permission:
              type: string
            to:
              type: string
          required:
          - "on"
          - permission
          - to
          type: object
        status:
          description: MySQLGrantStatus defines the observed state of MySQLGrant
          properties:
            error:
              type: string
            granted:
              type: boolean
          required:
          - error
          - granted
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
