---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlusers.api.edb-operator.com
spec:
  group: api.edb-operator.com
  names:
    kind: MySQLUser
    listKind: MySQLUserList
    plural: mysqlusers
    singular: mysqluser
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name: { type: string }
            host: { type: string }
            externalDatabaseRef: { type: object }
  subresources:
    status: {}
