apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqldatabases.api.edb-operator.com
spec:
  group: api.edb-operator.com
  names:
    kind: MySQLDatabase
    listKind: MySQLDatabaseList
    plural: mysqldatabases
    singular: mysqldatabase
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
