apiVersion: apps/v1
kind: Deployment
metadata:
  name: edb-operator
  namespace: edb-operator
  labels:
    operator: edb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      operator: edb-operator
  template:
    metadata:
      labels:
        operator: edb-operator
    spec:
      serviceAccountName: edb-operator
      containers:
        - name: edb-operator
          # Replace this with the built image name
          image: unlawfulmonad/edb-operator:latest
          imagePullPolicy: Always
          command:
            - edb-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "edb-operator"
