kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edb-operator
subjects:
- kind: ServiceAccount
  name: edb-operator
  namespace: edb-operator
roleRef:
  kind: ClusterRole
  name: edb-operator
  apiGroup: rbac.authorization.k8s.io
