---
apiVersion: v1
kind: Secret
metadata:
  name: edb-mysql-root-password
data:
  # This is just 'mysql'.
  mysql-password: bXlzcWw=
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edb-mysql-root-password
                  key: mysql-password
